kind: pipeline
name: default
type: docker
steps:
  - name: tests
    image: node:20-alpine
    environment:
      GATSBY_DEFAULT_SITE_URL: http://localhost
    commands:
      - npm install
      - npm run build
