kind: pipeline
name: default

steps:
  - name: tests
    image: node:18-alpine
    environment:
      GATSBY_DEFAULT_SITE_URL: http://localhost
    commands:
      - npm install
      - npm run build
