name: Validate examples
on:
  push:
    paths:
      - 'examples/**'
  pull_request:
    paths:
      - 'examples/**'
jobs:
  kind-validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up kind
        uses: engineerd/setup-kind@v0.5.0
        with:
          version: v0.20.0

      - name: Create kind cluster
        run: |
          kind create cluster --name examples --wait 60s

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: '1.27.3'

      - name: Apply examples
        run: |
          kubectl apply -f examples/basic-nginx/deployment.yaml

      - name: Wait for pods ready
        run: |
          kubectl wait --for=condition=ready pod -l app=example-nginx --timeout=120s

      - name: Smoke test service
        run: |
          kubectl get svc example-nginx -o yaml
